### ユーザー情報取得
GET http://localhost:8000/api/users/1
Accept: application/json


### 指定範囲のレベル
GET http://localhost:8000/api/users/index?min_level=5&max_level=25
Accept: application/json


### 指定したユーザーIDの所持アイテム情報を取得
GET http://localhost:8000/api/users/items/2
Accept: application/json


### 指定したユーザーIDのフォローリストを取得
GET http://localhost:8000/api/users/follows/1
Accept: application/json


### 全アイテムのリスト取得
GET http://localhost:8000/api/items/index
Accept: application/json


### メールの全マスターデータを取得
GET http://localhost:8000/api/mails/index
Accept: application/json


### 指定したユーザーの受信メールを取得
GET http://localhost:8000/api/mails/receive/5
Accept: application/json
